=== kidroca/Databases/XML Basics/students-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  targetNamespace="urn:students" 
  xmlns="urn:students"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="textField">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z\d].+" />
      <xs:minLength value="2" />
      <xs:maxLength value="25" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="students">
    <xs:complexType>
      <xs:choice>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z][a-z]+? [A-Z][a-z]+?" />
                    <xs:minLength value="4" />
                    <xs:maxLength value="20" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="sex">
                <xs:simpleType>
                  <xs:restriction base ="xs:string">
                    <xs:enumeration value="Male" />
                    <xs:enumeration value="Female" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="birth-date" type="xs:date" />
              <xs:element name="phone">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\+\d{3}(?:-|[ ])\d{1,2}(?:-|[ ])\d{3}(?:-|[ ])\d{3,5}" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="email">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="^[A-Za-z0-9]+(?!\w*\.{2})(?:[\w\-]|[.])*[A-Za-z0-9]+[@][A-Za-z]+(?!\w*\.{2})(?:[A-Za-z\-]|\.)*\.[A-Za-z]+$" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="course" type="textField" />
              <xs:element name="specialty" type="textField" />
              <xs:element name="faculty-number">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\d{10}" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="exam" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="textField" />
                          <xs:element name="score" type="xs:unsignedShort" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="enrollment-info">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enrollment-date" type="xs:date" />
                    <xs:element name="exam-score" type="xs:unsignedInt" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="endorsements" type="textField" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== kidroca/Databases/XML Basics/students.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="students-stylesheet.xsl" type="text/xsl"?>
<students
  xmlns="urn:students"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="students students-schema.xsd">
  <student>
    <name>Pesho Kolev</name>
    <sex>Male</sex>
    <birth-date>1944-07-23</birth-date>
    <phone>+359-2-456-1231</phone>
    <email>p.kolev@email.com</email>
    <course>HQC</course>
    <specialty>Software Engineering</specialty>
    <faculty-number>0912325237</faculty-number>
    <exams>
      <exam>
        <name>C# 1</name>
        <score>1000</score>
      </exam>
    </exams>
    <enrollment-info>
      <enrollment-date>2013-01-02</enrollment-date>
      <exam-score>1000</exam-score>
    </enrollment-info>
    <endorsements>Good boy</endorsements>
  </student>
  <student>
    <name>Kliment Ohridski</name>
    <sex>Male</sex>
    <birth-date>0840-06-15</birth-date>
    <phone>+359-32-886-893</phone>
    <email>glagolitza@gmail.com</email>
    <course>Cyrillic Languages</course>
    <specialty>Scientist and Bishop</specialty>
    <faculty-number>0000000004</faculty-number>
    <exams>
      <exam>
        <name>Glagolitza</name>
        <score>1000</score>
      </exam>
      <exam>
        <name>Kirilitza</name>
        <score>1000</score>
      </exam>
    </exams>
    <enrollment-info>
      <enrollment-date>0859-01-02</enrollment-date>
      <exam-score>500</exam-score>
    </enrollment-info>
    <endorsements>25th Novembre</endorsements>
  </student>
</students>
